# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ousema.bouaneni@polytechnique.edu
author_name: Ousema Bouaneni
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupyterlab-dsge
project_short_description: A Jupyterlab extension.
python_name: jupyterlab_dsge
repository: ""
test: true
