[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tasks]
install = "rm -rf \".pixi/envs/default/share/jupyter/labextensions/jupyter-dynare\"; pip install -ve . && jupyter labextension develop --overwrite ."
lab = {cmd = "jupyter lab", depends-on = ["install"] }

[dependencies]
nodejs = ">=24.4.0,<24.5"
jupyter_server = ">=2.4.0,<3"
pip = ">=25.1.1,<26"
jupyterlab = ">=4.0.0,<5"
dyno = { path = "../dyno.py" }
xeus-python = ">=0.17.4,<0.18"
nlohmann_json = "==3.11.3"

[pypi-dependencies]
jupyter_dynare = { path = ".", editable = true }


[package]
name = "dyno"
version = "0.1.5"

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies] 
hatchling = "==1.26.3"
